services:
  authorization:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authorization
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: identity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - authorization

volumes:
  pg_data:
